### ISSUE TITLE
Problem with opening cert store in IIS - works in IIS Express

### ISSUE THREAD

**Issue by shogedal** [RickardPettersson/swish-api-csharp#24] opened 2022-09-28 11:55 UTC
I run my IIS app pool with the ApplicationPoolIdentity and it cannot open the store in PrepareHttpClientAndHandler():

Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Access is denied. at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags) at SwishApi.Client.PrepareHttpClientAndHandler(HttpClientHandler& handler, HttpClient& client)

If I don't bother storing the "root certificates" I cannot communicate at all:

Authentication failed because the remote party sent a TLS alert HandshakeFailure

Does anyone have any other plan than to add the "root certs" to the intermediate certificate store of "local computer"?

**Comment by RickardPettersson** [comment] 2022-09-28 12:13
Sounds not good but if you try the new code that now exist where you put in the certificate as a stream and set UseMachineKeySet on the ClientCertificate object then its not using the store instead loading the cert from stream and then use the password passed in the ClientCertificate object.

Not sure if it going to work but its newest code fix for Azure problem that i not tested yet by my self.

**Comment by shogedal** [comment] 2022-09-28 12:34
I haven't upgrade to the latest version in my project, but I changed PrepareHttpClientAndHandler to just do this

                var cert = new X509Certificate2(_certificate.Content, _certificate.Password, X509KeyStorageFlags.MachineKeySet);
                handler.ClientCertificates.Add(cert);

And it still doesn't work unless the "root certs" are in place.

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'. ---> System.ComponentModel.Win32Exception (0x80090326): Det mottagna meddelandet var oväntat eller felaktigt formaterat. --- End of inner exception stack trace

**Comment by RickardPettersson** [comment] 2022-10-20 08:57
Tested to run latest code?

**Comment by shogedal** [comment] 2022-10-20 09:40
Unfortunately I have not had the time, but I finally got my Web Hotel to fix the "load user profile" issue that was still to fix. Previously the imported the SEB certificates to the cert store, but that wasn't enough.
We're up and running, so I will not take time to elaborate further right now.

Vänligen,
Stefan Hogedal

+46 704-456560

Om meddelandet känns kort eller obegripligt kan det bero på att det författades på en Samsung A52a.

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by linus-dev** [comment] 2022-11-30 18:01
> I haven't upgrade to the latest version in my project, but I changed PrepareHttpClientAndHandler to just do this
> 
> ```
>             var cert = new X509Certificate2(_certificate.Content, _certificate.Password, X509KeyStorageFlags.MachineKeySet);
>             handler.ClientCertificates.Add(cert);
> ```
> 
> And it still doesn't work unless the "root certs" are in place.
> 
> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'. ---> System.ComponentModel.Win32Exception (0x80090326): Det mottagna meddelandet var oväntat eller felaktigt formaterat. --- End of inner exception stack trace

Hi,

I have the same issue as you. Could you please explain a bit more how you solved it? And by "root certs", is this the cert I get from swish called "Swish_TLS_RootCA.pem"? 
Also, what web hotel do you use?
Thanks!

**Comment by shogedal** [comment] 2022-11-30 18:10
I struggled a lot with my Web hotel Loopia and "googling". In the end I think that not only did I need the two SEB certificates installed on the server but also having them fix the apppool to use an account with a profile.

Vänligen,
Stefan Hogedal

+46 704-456560

Om meddelandet känns kort eller obegripligt kan det bero på att det författades på en Samsung A52a.

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by entrieapp** [comment] 2022-11-30 20:50
Ok. I've reached out to my web hotel, hopefully they are able to do the same.
 When I load my cert it throws an error
`Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The specified network password is not correct.`

Could this be caused by the app pool? I have tried with normal string password and SecureString. I have verified that the value of the password is "swish" so I don't see any other cause for this.

**Comment by linus-dev** [comment] 2022-11-30 20:51
Ok. I've reached out to my web hotel, hopefully they are able to do the same.
When I load my cert it throws an error
`Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The specified network password is not correct.`

Could this be caused by the app pool? I have tried with normal string password and SecureString. I have verified that the value of the password is "swish" so I don't see any other cause for this.

**Comment by shogedal** [comment] 2022-12-01 12:44
I am not 100% sure but I think I got that message as a result of some other miss. You know that it's only with the demo cert the password is that one?

Vänligen,
Stefan Hogedal

+46 704-456560

Om meddelandet känns kort eller obegripligt kan det bero på att det författades på en Samsung A52a.

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by entrieapp** [comment] 2022-12-01 16:36
I followed this guide: https://github.com/RickardPettersson/swish-api-csharp/wiki/Hantera-certifikat
Jsut for simplicity, I inserted "swish" as the password in the last step when creating a .p12-file. I assume this is the password I should use in my application.

**Comment by linus-dev** [comment] 2022-12-01 16:36
I followed this guide: https://github.com/RickardPettersson/swish-api-csharp/wiki/Hantera-certifikat
Jsut for simplicity, I inserted "swish" as the password in the last step when creating a .p12-file. I assume this is the password I should use in my application.

**Comment by RickardPettersson** [comment] 2022-12-08 16:58
@linus-dev  did you got it to work?

I was now setup a client´s certificate and got this problem, i tested recreate the cert 5 times now to see so i am not doing something wrong or but i getting "The specified network password is not correct.". I tried to set a simple password as swish i tested to do a harder but no different when the code try to load from the .p12 file with password i set its get the error.

It is in the .net code i getting it but i thinking if GetSwish AB done some changes to the cert when you upload the CSR file and ghet the pem file...

**Comment by shogedal** [comment] 2022-12-08 19:22
I'm "off line" but I think I saw that message during my struggle and that it meant something else than choosing the right password.

Vänligen,
Stefan Hogedal

+46 704-456560

Om meddelandet känns kort eller obegripligt kan det bero på att det författades på en Samsung A52a.

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by linus-dev** [comment] 2022-12-14 16:52
@RickardPettersson No I did not... I haven't tried it on my local machine yet though. Maybe it could be some kind of permission issue? Hopefully I can try a little bit more when I have more time. If Swish made any changes I would be happy to know!

**Comment by RickardPettersson** [comment] 2022-12-19 09:08
This is very intresting, i have now tested using openssl both 32-bit and 64-bit also used java keytool that i got a tutorial from GetSwish AB with instruction for and i used the windows tool they saying to use on the certifikat portal and then openssl to generate p12 file. 

I have also tested all different generated certifikates both in .Net 7, .Net 6 and .Net 4.5.2 and all give me the "network password is failed" error message.

I dont know what have happend and why this is, starting to think if there is needed a older windows open ssl version or something.

I have personally got this to work with my wiki tutorial for like 2 years ago or what it can be but now its totally failing.

**Comment by RickardPettersson** [comment] 2022-12-19 11:32
After some more reasearch and more testing i tested OpenSSL v1.1.1s and got it to work, no more "network password is failed" message,  i updated the wiki for handling certifikate.

**Comment by RickardPettersson** [comment] 2023-05-12 13:02
Can we close this issue?

**Comment by shogedal** [comment] 2023-05-12 13:10
I have found a solution in configuring IIS. I wonder if there is one that is just about creating the cert file in another way, but let's close this.

Vänligen,
Stefan Hogedal

+46 704-456560

Om meddelandet känns kort eller obegripligt kan det bero på att det författades på en Samsung A52a.

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Closed as completed** 2023-05-12 13:15 UTC
